project:
  type: book
  output-dir: _book

book:
  title: "MOSAIKS Training Manual"
  author: 
    - name: Cullen Molitor
      affiliations: "Center for Effective Global Action (CEGA)"
      url: https://emlab.ucsb.edu/about/our-team/cullen-molitor
    - name:  Tamma Carleton
      affiliations: "UC Berkeley Department of Agricultural and Resource Economics"
      url: https://are.berkeley.edu/users/tamma-carleton
    - name:  Esther Rolf
      affiliations: "UC Boulder College of Engineering and Applied Science"
      url: https://www.colorado.edu/cs/esther-rolf
  reader-mode: true

  page-footer:
    left: |
      MOSAIKS Training Manual
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://cullen-molitor.github.io/MOSAIKS-Training-Manual/
  repo-url: https://github.com/cullen-molitor/MOSAIKS-Training-Manual
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - intro-compute.qmd
        - intro-mosaiks.qmd
        - intro-api.qmd
        - intro-demo.qmd
    - part: labels.qmd  
      chapters:
        - labels-100-maps.qmd
        - labels-over-time.qmd
        - labels-data-prep.qmd
        - labels-survey.qmd
        - mosaiks-demo-2.qmd
        - interactive-agriculture.qmd
    - part: satellite.qmd  
      chapters:
        - satellite-imagery.qmd
        - satellite-processing.qmd
    - part: features.qmd  
      chapters:
        - features-api.qmd
        - features-computing.qmd
    - part: model.qmd  
      chapters:
        - model-choice.qmd
        - model-spatial.qmd
        - model-temporal.qmd
    - part: uncertainty.qmd  
      chapters:
        - uncertainty-intro.qmd
        - uncertainty-ethics.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: slate
    highlight-style: atom-one
    css: style.scss
    code-link: true    
    callout-appearance: simple

filters:
    - openlinksinnewpage

execute:
  freeze: auto
  echo: true
  message: false
  warning: false



