project:
  type: book

book:
  reader-mode: true
  favicon: "images/sat_earth.png"
  cover-image: "images/sat_earth.png"
  site-url: https://cullen-molitor.github.io/MOSAIKS-Training-Manual/en/
  repo-url: https://github.com/cullen-molitor/MOSAIKS-Training-Manual
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd

tbl-cap-location: bottom

bibliography: references.bib

format:
  html:
    theme: 
      light: flatly
      dark: slate
    highlight-style: atom-one
    css: style.scss
    code-link: true    
    callout-appearance: simple

filters:
    - openlinksinnewpage

execute:
  freeze: auto
  echo: true
  message: false
  warning: false