name: Publish to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          submodules: true  # If your project uses submodules
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Configure Git User
      - name: Configure Git
        run: |
          git config --global user.name "cullen-molitor"
          git config --global user.email "cullen.molitor@gmail.com"

      # Publish to GitHub Pages
      - name: Publish to GitHub Pages
        run: quarto publish gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
