name: Deploy Quarto Book to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Dependencies
        run: sudo apt-get install -y pandoc

      - name: Render and Publish
        run: quarto publish gh-pages
